### ISSUE TITLE
Demo website does not allow access to local triplestores without HTTPS

### ISSUE THREAD

**Issue by berezovskyi** [sebferre/sparklis#10]
Hello Sébastien! To access a triplestore at a local URI, the web server must use TLS. When I try to open https://www.irisa.fr/LIS/ferre/sparklis/osparklis.html, I get redirected to a non-HTTPS page. Would it be possible to add TLS cert to the website, please? Thank you!

P.S. Tested this with http://jiemakel.github.io/aether/#/generate-menu. Has the same CORS error but goes away if I open https://jiemakel.github.io/aether/#/generate-menu instead.

Chrome 98.0.4758.80

**Comment by sebferre** [comment]
Hello, I'm surprised because it is allowed for a non-HTTPS page to call HTTPS server (contrary to the inverse). 
A number of pre-defined SPARQL endpoints are HTTPS, and they work fine in the non-HTTPS Sparklis page.
The redirection was added precisely so that non-HTTPS endpoints can still be explored.

However, it is my plan to switch to HTTPS, as soon as I manage to run my own fuseki endpoints in HTTPS mode (help welcome!).

A quick solution to your problem is to download the contents of the `webapp/` dir, and to open your local copy if `osparklis.html` in your browser. This should fix it.
