### ISSUE TITLE
SPARQL to Natural Language

### ISSUE THREAD

**Issue by firmao** [sebferre/sparklis#11]
First of all, congratulations on your fantastic software called SPARKLIS.

Is there a way to convert a SPARQL query to Natural language using SPARKLIS?

Suggestions/alternative solutions are welcome :)

Thanks in advance,
Andre Valdestilhas

**Comment by sebferre** [comment]
You can use the SPARQL query as a guide when navigating in Sparklis, until you get an equivalent SPARQL query in the YASGUI view. In the configuration panel "Language and labels", set blank the properties for the labels of entities, classes... so that the suggestions are displayed according to their URIs, and hence easily matched with the URIs in your SPARQL query.
When you're done with building the query, reset the label configuration to the labelling properties of your dataset. You now get a query is (coarse) natural language in the Sparklis query widget.
